FROM node:24-alpine AS build
WORKDIR /app
COPY src/frontend/healthcare-gis-web/package*.json ./
RUN npm ci
COPY src/frontend/healthcare-gis-web/ ./
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/dist/healthcare-gis-web/browser /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
